# Generated by Django 2.1.7 on 2019-03-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190326_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_holder', models.CharField(max_length=120)),
                ('contact_person', models.TextField(blank=True, null=True)),
                ('timeadded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
