# Generated by Django 2.1.7 on 2019-03-27 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_license'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='r_holder',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='license',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='license',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='license',
            name='rights_holder',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
